let finals = [
    [{
        "tourney_name":"Vina del Mar",
        "surface":"Clay",
        "round":"F",
        "tourney_date":20030210,
        "minutes":102,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Munich",
        "surface":"Clay",
        "round":"F",
        "tourney_date":20030428,
        "minutes":56,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Newport",
        "surface":"Grass",
        "round":"F",
        "tourney_date":20030707,
        "minutes":99,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Nottingham",
        "surface":"Grass",
        "round":"F",
        "tourney_date":20030616,
        "minutes":57,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Acapulco",
        "surface":"Clay",
        "round":"F",
        "minutes":64,
        "tourney_date":20040301,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Adelaide",
        "surface":"Hard",
        "round":"F",
        "minutes":57,
        "tourney_date":20040105,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Auckland",
        "surface":"Hard",
        "round":"F",
        "minutes":135,
        "tourney_date":20040112,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Dubai",
        "surface":"Hard",
        "round":"F",
        "minutes":95,
        "tourney_date":20040301,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Moscow",
        "surface":"Carpet",
        "round":"F",
        "minutes":109,
        "tourney_date":20041011,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Washington",
        "surface":"Hard",
        "round":"F",
        "minutes":77,
        "tourney_date":20040816,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Delray Beach",
        "surface":"Hard",
        "round":"F",
        "minutes":104,
        "tourney_date":20040913,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Newport",
        "surface":"Grass",
        "round":"F",
        "minutes":108,
        "tourney_date":20040705,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"s Hertogenbosch",
        "surface":"Grass",
        "round":"F",
        "minutes":62,
        "tourney_date":20040614,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Sopot",
        "surface":"Clay",
        "round":"F",
        "minutes":96,
        "tourney_date":20040809,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Valencia",
        "surface":"Clay",
        "round":"F",
        "minutes":96,
        "tourney_date":20040412,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Vienna",
        "surface":"Hard",
        "round":"F",
        "minutes":215,
        "tourney_date":20041011,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Buenos Aires",
        "surface":"Clay",
        "tourney_date":20050207,
        "round":"F",
        "minutes":92,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Kitzbuhel",
        "surface":"Clay",
        "tourney_date":20050725,
        "round":"F",
        "minutes":161,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Los Angeles",
        "surface":"Hard",
        "tourney_date":20050725,
        "round":"F",
        "minutes":88,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Miami Masters",
        "surface":"Hard",
        "tourney_date":20050321,
        "round":"F",
        "minutes":223,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"New Haven",
        "surface":"Hard",
        "tourney_date":20050822,
        "round":"F",
        "minutes":98,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"s Hertogenbosch",
        "surface":"Grass",
        "tourney_date":20050613,
        "round":"F",
        "minutes":69,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"St. Poelten",
        "surface":"Clay",
        "tourney_date":20050516,
        "round":"F",
        "minutes":135,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Acapulco",
        "surface":"Clay",
        "tourney_date":20050221,
        "round":"F",
        "minutes":52,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "tourney_date":20050418,
        "round":"F",
        "minutes":176,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Bastad",
        "surface":"Clay",
        "tourney_date":20050704,
        "round":"F",
        "minutes":120,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Beijing",
        "surface":"Hard",
        "tourney_date":20050912,
        "round":"F",
        "minutes":116,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Canada Masters",
        "surface":"Hard",
        "tourney_date":20050808,
        "round":"F",
        "minutes":118,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Casablanca",
        "surface":"Clay",
        "tourney_date":20050404,
        "round":"F",
        "minutes":78,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Costa Do Sauipe",
        "surface":"Clay",
        "tourney_date":20050214,
        "round":"F",
        "minutes":126,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Madrid Masters",
        "surface":"Hard",
        "tourney_date":20051017,
        "round":"F",
        "minutes":233,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Memphis",
        "surface":"Hard",
        "tourney_date":20050214,
        "round":"F",
        "minutes":98,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Monte Carlo Masters",
        "surface":"Clay",
        "tourney_date":20050411,
        "round":"F",
        "minutes":189,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Newport",
        "surface":"Grass",
        "tourney_date":20050704,
        "round":"F",
        "minutes":116,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rome Masters",
        "surface":"Clay",
        "tourney_date":20050502,
        "round":"F",
        "minutes":314,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Scottsdale",
        "surface":"Hard",
        "tourney_date":20050221,
        "round":"F",
        "minutes":81,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Stuttgart",
        "surface":"Clay",
        "tourney_date":20050718,
        "round":"F",
        "minutes":161,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Gstaad",
        "surface":"Clay",
        "tourney_date":20060710,
        "round":"F",
        "minutes":185,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Houston",
        "surface":"Clay",
        "tourney_date":20060410,
        "round":"F",
        "minutes":112,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Metz",
        "surface":"Hard",
        "tourney_date":20061002,
        "round":"F",
        "minutes":111,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Stockholm",
        "surface":"Hard",
        "tourney_date":20061009,
        "round":"F",
        "minutes":56,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Wimbledon",
        "surface":"Grass",
        "tourney_date":20060626,
        "round":"F",
        "minutes":178,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Zagreb",
        "surface":"Carpet",
        "tourney_date":20060130,
        "round":"F",
        "minutes":66,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Auckland",
        "surface":"Hard",
        "tourney_date":20060109,
        "round":"F",
        "minutes":61,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "tourney_date":20060424,
        "round":"F",
        "minutes":139,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Bucharest",
        "surface":"Clay",
        "tourney_date":20060911,
        "round":"F",
        "minutes":85,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Dubai",
        "surface":"Hard",
        "tourney_date":20060227,
        "round":"F",
        "minutes":113,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Monte Carlo Masters",
        "surface":"Clay",
        "tourney_date":20060417,
        "round":"F",
        "minutes":230,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Roland Garros",
        "surface":"Clay",
        "tourney_date":20060529,
        "round":"F",
        "minutes":182,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rome Masters",
        "surface":"Clay",
        "tourney_date":20060508,
        "round":"F",
        "minutes":305,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Adelaide",
        "surface":"Hard",
        "tourney_date":20070101,
        "round":"F",
        "minutes":147,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Basel",
        "surface":"Hard",
        "tourney_date":20071022,
        "round":"F",
        "minutes":61,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Buenos Aires",
        "surface":"Clay",
        "tourney_date":20070219,
        "round":"F",
        "minutes":64,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Chennai",
        "surface":"Hard",
        "tourney_date":20070101,
        "round":"F",
        "minutes":61,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Hamburg Masters",
        "surface":"Clay",
        "tourney_date":20070514,
        "round":"F",
        "minutes":115,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Las Vegas",
        "surface":"Hard",
        "tourney_date":20070226,
        "round":"F",
        "minutes":101,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Paris Masters",
        "surface":"Hard",
        "tourney_date":20071028,
        "round":"F",
        "minutes":70,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"St. Petersburg",
        "surface":"Carpet",
        "tourney_date":20071022,
        "round":"F",
        "minutes":77,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Wimbledon",
        "surface":"Grass",
        "tourney_date":20070625,
        "round":"F",
        "minutes":225,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "tourney_date":20070423,
        "round":"F",
        "minutes":101,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Indian Wells Masters",
        "surface":"Hard",
        "tourney_date":20070305,
        "round":"F",
        "minutes":94,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Monte Carlo Masters",
        "surface":"Clay",
        "tourney_date":20070415,
        "round":"F",
        "minutes":95,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Roland Garros",
        "surface":"Clay",
        "tourney_date":20070528,
        "round":"F",
        "minutes":190,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rome Masters",
        "surface":"Clay",
        "tourney_date":20070507,
        "round":"F",
        "minutes":84,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Stuttgart",
        "surface":"Clay",
        "tourney_date":20070716,
        "round":"F",
        "minutes":129,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Chennai",
        "surface":"Hard",
        "tourney_date":20071231,
        "round":"F",
        "minutes":57,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Dubai",
        "surface":"Hard",
        "tourney_date":20080303,
        "round":"F",
        "minutes":115,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Kitzbuhel",
        "surface":"Clay",
        "tourney_date":20080714,
        "round":"F",
        "minutes":59,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Miami Masters",
        "surface":"Hard",
        "tourney_date":20080327,
        "round":"F",
        "minutes":91,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Nottingham",
        "surface":"Grass",
        "tourney_date":20080616,
        "round":"F",
        "minutes":142,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Sydney",
        "surface":"Hard",
        "tourney_date":20080107,
        "round":"F",
        "minutes":83,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "tourney_date":20080428,
        "round":"F",
        "minutes":134,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Beijing Olympics",
        "surface":"Hard",
        "tourney_date":20080811,
        "round":"F",
        "minutes":143,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Canada Masters",
        "surface":"Hard",
        "tourney_date":20080721,
        "round":"F",
        "minutes":90,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Hamburg Masters",
        "surface":"Clay",
        "tourney_date":20080511,
        "round":"F",
        "minutes":172,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Monte Carlo Masters",
        "surface":"Clay",
        "tourney_date":20080420,
        "round":"F",
        "minutes":103,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Queen's Club",
        "surface":"Grass",
        "tourney_date":20080609,
        "round":"F",
        "minutes":136,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Roland Garros",
        "surface":"Clay",
        "tourney_date":20080525,
        "round":"F",
        "minutes":108,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rotterdam",
        "surface":"Hard",
        "tourney_date":20080218,
        "round":"F",
        "minutes":129,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Umag",
        "surface":"Clay",
        "tourney_date":20080714,
        "round":"F",
        "minutes":171,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Wimbledon",
        "surface":"Grass",
        "tourney_date":20080623,
        "round":"F",
        "minutes":288,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Brisbane",
        "surface":"Hard",
        "tourney_date":20090104,
        "round":"F",
        "minutes":138,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Costa Do Sauipe",
        "surface":"Clay",
        "tourney_date":20090209,
        "round":"F",
        "minutes":133,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Houston",
        "surface":"Clay",
        "tourney_date":20090406,
        "round":"F",
        "minutes":124,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Kuala Lumpur",
        "surface":"Hard",
        "tourney_date":20090928,
        "round":"F",
        "minutes":95,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Los Angeles",
        "surface":"Hard",
        "tourney_date":20090727,
        "round":"F",
        "minutes":88,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Lyon",
        "surface":"Hard",
        "tourney_date":20091026,
        "round":"F",
        "minutes":97,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Madrid Masters",
        "surface":"Clay",
        "tourney_date":20090510,
        "round":"F",
        "minutes":86,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Marseille",
        "surface":"Hard",
        "tourney_date":20090216,
        "round":"F",
        "minutes":104,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Rotterdam",
        "surface":"Hard",
        "tourney_date":20090209,
        "round":"F",
        "minutes":111,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Shanghai Masters",
        "surface":"Hard",
        "tourney_date":20091011,
        "round":"F",
        "minutes":123,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"St. Petersburg",
        "surface":"Hard",
        "tourney_date":20091025,
        "round":"F",
        "minutes":139,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Sydney",
        "surface":"Hard",
        "tourney_date":20090112,
        "round":"F",
        "minutes":136,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Australian Open",
        "surface":"Hard",
        "tourney_date":20090119,
        "round":"F",
        "minutes":259,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "tourney_date":20090420,
        "round":"F",
        "minutes":106,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Indian Wells Masters",
        "surface":"Hard",
        "tourney_date":20090312,
        "round":"F",
        "minutes":81,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Monte Carlo Masters",
        "surface":"Clay",
        "tourney_date":20090412,
        "round":"F",
        "minutes":163,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"New Haven",
        "surface":"Hard",
        "tourney_date":20090823,
        "round":"F",
        "minutes":96,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rome Masters",
        "surface":"Clay",
        "tourney_date":20090427,
        "round":"F",
        "minutes":123,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Vienna",
        "surface":"Hard",
        "tourney_date":20091026,
        "round":"F",
        "minutes":93,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Doha",
        "surface":"Hard",
        "round":"F",
        "minutes":163,
        "tourney_date":20100104,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Zagreb",
        "surface":"Hard",
        "round":"F",
        "minutes":159,
        "tourney_date":20100201,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Nice",
        "surface":"Clay",
        "round":"F",
        "minutes":157,
        "tourney_date":20100516,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Hamburg",
        "surface":"Clay",
        "round":"F",
        "minutes":90,
        "tourney_date":20100719,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Metz",
        "surface":"Hard",
        "round":"F",
        "minutes":67,
        "tourney_date":20100920,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Bangkok",
        "surface":"Hard",
        "round":"F",
        "minutes":116,
        "tourney_date":20100927,
        "winner_hand":"R",
        "loser_hand":"L"
    },{
        "tourney_name":"Johannesburg",
        "surface":"Hard",
        "round":"F",
        "minutes":74,
        "tourney_date":20100201,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Santiago",
        "surface":"Clay",
        "round":"F",
        "minutes":125,
        "tourney_date":20100201,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"San Jose",
        "surface":"Hard",
        "round":"F",
        "minutes":131,
        "tourney_date":20100208,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Marseille",
        "surface":"Hard",
        "round":"F",
        "minutes":71,
        "tourney_date":20100215,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Barcelona",
        "surface":"Clay",
        "round":"F",
        "minutes":124,
        "tourney_date":20100419,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Rome Masters",
        "surface":"Clay",
        "round":"F",
        "minutes":104,
        "tourney_date":20100425,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Madrid Masters",
        "surface":"Clay",
        "round":"F",
        "minutes":131,
        "tourney_date":20100509,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Roland Garros",
        "surface":"Clay",
        "round":"F",
        "minutes":138,
        "tourney_date":20100524,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Eastbourne",
        "surface":"Grass",
        "round":"F",
        "minutes":67,
        "tourney_date":20100613,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Wimbledon",
        "surface":"Grass",
        "round":"F",
        "minutes":133,
        "tourney_date":20100621,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"US Open",
        "surface":"Hard",
        "round":"F",
        "minutes":223,
        "tourney_date":20100830,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Tokyo",
        "surface":"Hard",
        "round":"F",
        "minutes":77,
        "tourney_date":20101004,
        "winner_hand":"L",
        "loser_hand":"R"
    },{
        "tourney_name":"Vienna",
        "surface":"Hard",
        "round":"F",
        "minutes":168,
        "tourney_date":20101025,
        "winner_hand":"L",
        "loser_hand":"R"
    }]
];